# Generated by Django 5.2.9 on 2025-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_cover_photo_profile_gender_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10, verbose_name='preferred language'),
        ),
    ]
