# Generated by Django 5.2.9 on 2025-12-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_level_profile_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_quest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
    ]
