# Generated by Django 5.2.9 on 2026-01-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_last_quest_date_profile_streak_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_3d',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/3d/', verbose_name='3D avatar'),
        ),
    ]
