# Generated by Django 5.2.9 on 2026-01-04 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(max_length=500, upload_to='videos/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('processing_progress', models.IntegerField(default=0, help_text='Progress percentage 0-100')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, help_text='Detected language code', max_length=10, null=True)),
                ('caption_enabled', models.BooleanField(default=True)),
                ('caption_language_mode', models.CharField(choices=[('original', 'Original Only'), ('translated', 'Translated Only'), ('both', 'Both Languages')], default='original', max_length=20)),
                ('translation_language', models.CharField(default='en', help_text='Target translation language', max_length=10)),
                ('thumbnail_template', models.CharField(choices=[('clean', 'Clean Title Overlay'), ('face', 'Face-Focused'), ('gradient', 'Gradient Background'), ('creator', 'Creator Style')], default='clean', max_length=50)),
                ('thumbnail_text', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_thumbnail', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThumbnailOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumbnail_options/%Y/%m/')),
                ('template', models.CharField(max_length=50)),
                ('frame_timestamp', models.FloatField(help_text='Video timestamp of the frame')),
                ('has_face', models.BooleanField(default=False)),
                ('emotion_detected', models.CharField(blank=True, max_length=50, null=True)),
                ('quality_score', models.FloatField(default=0.0, help_text='AI quality score 0-1')),
                ('overlay_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_options', to='videos.video')),
            ],
            options={
                'ordering': ['-quality_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaptionProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage 0-100')),
                ('chunk_index', models.IntegerField(default=0, help_text='For long videos, which chunk')),
                ('total_chunks', models.IntegerField(default=1)),
                ('source_language', models.CharField(blank=True, max_length=10, null=True)),
                ('target_language', models.CharField(blank=True, max_length=10, null=True)),
                ('captions_generated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_jobs', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='Language code (en, ml, etc.)', max_length=10)),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('text', models.TextField()),
                ('confidence', models.FloatField(default=0.0, help_text='AI confidence score 0-1')),
                ('is_translated', models.BooleanField(default=False)),
                ('original_text', models.TextField(blank=True, help_text='Original text if translated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='videos.video')),
            ],
            options={
                'ordering': ['video', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.videocomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videos.video')),
            ],
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at'], name='videos_vide_created_1f1e45_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['user', '-created_at'], name='videos_vide_user_id_260722_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status'], name='videos_vide_status_107761_idx'),
        ),
        migrations.AddIndex(
            model_name='caption',
            index=models.Index(fields=['video', 'start_time'], name='videos_capt_video_i_9540c4_idx'),
        ),
        migrations.AddIndex(
            model_name='caption',
            index=models.Index(fields=['video', 'language'], name='videos_capt_video_i_8d8acc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videolike',
            unique_together={('video', 'user')},
        ),
    ]
