# Generated by Django 5.2.9 on 2026-01-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnailoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_options/%Y/%m/'),
        ),
    ]
