# Generated by Django 5.2.9 on 2026-02-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_thumbnailoption_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='scheduled_for',
            new_name='scheduled_at',
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('failed', 'Failed')], default='uploading', max_length=20),
        ),
    ]
