# Generated by Django 5.2.9 on 2025-12-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('reaction', 'Reaction'), ('follow_request', 'Follow Request'), ('follow_accept', 'Follow Accept'), ('follow', 'New Follower')], max_length=50),
        ),
    ]
