# Generated by Django 5.2.9 on 2026-01-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comment',
            name='ai_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='toxicity',
            field=models.CharField(choices=[('none', 'None'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=10),
        ),
    ]
