# Generated by Django 5.2.9 on 2026-01-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comment_ai_confidence_comment_ai_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='music_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
