# Generated by Django 5.2.9 on 2026-01-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postmedia_captions'),
        ('posts', '0008_post_music_info'),
    ]

    operations = [
    ]
