# Generated by Django 5.2.9 on 2026-01-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_merge_0002_postmedia_captions_0008_post_music_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether post is visible to public'),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='When to publish this post', null=True),
        ),
    ]
