# Generated by Django 5.2.9 on 2026-02-08 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_is_public_remove_post_scheduled_for_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLocationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the image file', max_length=64, unique=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark_confidence', models.FloatField(default=0.0)),
                ('city_confidence', models.FloatField(default=0.0)),
                ('country_confidence', models.FloatField(default=0.0)),
                ('detected_location', models.CharField(blank=True, help_text="Formatted location string (e.g., 'Eiffel Tower, France')", max_length=512, null=True)),
                ('overall_confidence', models.FloatField(default=0.0, help_text='Confidence of the best detected location')),
                ('raw_response', models.JSONField(blank=True, help_text='Raw API response for debugging', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'image_location_cache',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['image_hash'], name='image_locat_image_h_5d5361_idx'), models.Index(fields=['created_at'], name='image_locat_created_5b4760_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_location', models.CharField(blank=True, help_text="Formatted location for display (e.g., '📍 Eiffel Tower, France')", max_length=512, null=True)),
                ('is_detected', models.BooleanField(default=False, help_text='Whether location was successfully detected')),
                ('detection_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_location', 'No Location Detected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_cache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.imagelocationcache')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_data', to='posts.post')),
            ],
            options={
                'db_table': 'post_locations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProhibitedWordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_words', models.TextField(help_text='Comma-separated list of words/phrases to prohibit')),
                ('reason', models.TextField(blank=True, help_text="User's reason for requesting these filters", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text="Admin's notes/reason for approval or rejection", null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_word_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting the word filter', on_delete=django.db.models.deletion.CASCADE, related_name='word_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prohibited_word_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProhibitedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='The prohibited word or phrase (stored in lowercase)', max_length=255)),
                ('variations', models.JSONField(blank=True, default=list, help_text="List of variations to also filter (e.g., ['fat', 'fatt', 'phatt'])")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this filter is currently active')),
                ('times_triggered', models.IntegerField(default=0, help_text='Number of times this word has filtered a comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this word filter', on_delete=django.db.models.deletion.CASCADE, related_name='prohibited_words', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, help_text='Original request that created this word', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_words', to='posts.prohibitedwordrequest')),
            ],
            options={
                'db_table': 'prohibited_words',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='FilteredComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_words', models.JSONField(default=list, help_text='List of prohibited words that matched in this comment')),
                ('is_visible_to_owner', models.BooleanField(default=False, help_text='Whether post owner can see this comment')),
                ('is_visible_to_public', models.BooleanField(default=False, help_text='Whether other users can see this comment')),
                ('is_visible_to_commenter', models.BooleanField(default=True, help_text='Commenter can always see their own comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filter_data', to='posts.comment')),
                ('commenter', models.ForeignKey(help_text='User who made the filtered comment', on_delete=django.db.models.deletion.CASCADE, related_name='filtered_comments_made', to=settings.AUTH_USER_MODEL)),
                ('post_owner', models.ForeignKey(help_text='Owner of the post (who has the word filter)', on_delete=django.db.models.deletion.CASCADE, related_name='filtered_comments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'filtered_comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post_owner', 'created_at'], name='filtered_co_post_ow_6673e5_idx'), models.Index(fields=['commenter', 'created_at'], name='filtered_co_comment_2ceaf2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prohibitedwordrequest',
            index=models.Index(fields=['user', 'status'], name='prohibited__user_id_ec037e_idx'),
        ),
        migrations.AddIndex(
            model_name='prohibitedwordrequest',
            index=models.Index(fields=['status', 'created_at'], name='prohibited__status_8fb266_idx'),
        ),
        migrations.AddIndex(
            model_name='prohibitedword',
            index=models.Index(fields=['user', 'is_active'], name='prohibited__user_id_bb12cf_idx'),
        ),
        migrations.AddIndex(
            model_name='prohibitedword',
            index=models.Index(fields=['word'], name='prohibited__word_2660ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prohibitedword',
            unique_together={('user', 'word')},
        ),
    ]
