# Generated by Django 5.2.9 on 2026-02-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_imagelocationcache_postlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteredcomment',
            name='is_visible_to_commenter',
            field=models.BooleanField(default=True, help_text='Commenter can always see their own comment (with warning)'),
        ),
        migrations.AlterField(
            model_name='filteredcomment',
            name='is_visible_to_owner',
            field=models.BooleanField(default=False, help_text='Whether post owner can see this comment (always False for filtered comments)'),
        ),
        migrations.AlterField(
            model_name='filteredcomment',
            name='is_visible_to_public',
            field=models.BooleanField(default=True, help_text='Whether other users can see this comment (True - filtering is only for post owner)'),
        ),
    ]
