# Generated by Django 5.2.9 on 2025-12-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_storylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
