# Generated by Django 5.2.9 on 2026-01-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_is_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='music_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
