# Generated by Django 5.2.9 on 2026-01-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_music_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='link_url',
            field=models.URLField(blank=True, help_text='Optional link to news or other content', null=True),
        ),
    ]
