# Generated by Django 5.2.9 on 2026-01-03 14:44

import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_story_link_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='link_description',
            field=models.TextField(blank=True, help_text='Link preview description', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='link_source',
            field=models.CharField(blank=True, help_text='Source name (e.g., CNN, BBC)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='link_thumbnail',
            field=models.URLField(blank=True, help_text='Link preview thumbnail', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='link_title',
            field=models.CharField(blank=True, help_text='Link preview title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('link', 'Link')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='link_url',
            field=models.URLField(blank=True, help_text='URL for link stories', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.FileField(blank=True, help_text='Upload an image or video', null=True, upload_to='stories/media/', validators=[stories.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='story',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10, null=True),
        ),
    ]
