# Generated by Django 5.2.9 on 2026-01-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_story_options_story_link_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='link_thumbnail',
            field=models.URLField(blank=True, help_text='Link preview thumbnail', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='link_url',
            field=models.TextField(blank=True, help_text='URL for link stories', null=True),
        ),
    ]
