# Generated by Django 5.2.9 on 2025-12-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_quest_difficulty_quest_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='category',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('travel', 'Travel'), ('learning', 'Learning'), ('photography', 'Photography'), ('mental-health', 'Mental Health'), ('music', 'Music'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
