# Generated by Django 5.2.9 on 2025-12-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_alter_quest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquest',
            name='is_daily_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
